### ISSUE TITLE
Hide Name, Email and Website

### ISSUE THREAD

**Issue by ravishakya** [ravishakya/comment-form-builder#1]
Add default name, email, website and comment and hide the field

**Comment by KTDesigns** [comment]
How do I hide the field?

**Comment by ravishakya** [comment]
That feature will be available in next version.

**Comment by ravishakya** [comment]
Hi,

I have added a feature to hide name, email and website. You can download the latest version [here](https://github.com/ravishakya/comment-form-builder/archive/master.zip)

[See screenshot](https://goo.gl/pbGhhY)

If everything is fine i will update the plugin in wordpress.org

**Comment by KTDesigns** [comment]
I've hidden the mentioned fields, but as it can't be hidden, is there a way rename the Comment label? I was looking for it in the PHP but am not sure where it gets defined.

**Comment by ravishakya** [comment]
1. I've hidden the mentioned fields, but as it can't be hidden

=> I have tested with the site you have given. It is working fine there. What fields are you trying to hide ? did you upload and checked the latest version from the github ? Can you send me a screenshot of the error you are having ?

**Comment by KTDesigns** [comment]
Sorry, I was not clear. I have hidden the Name, Email, and Website fields successfully. Because I cannot hide the Comments field, I would like to change what the label says. In fact, I'd like to be able to change the Name label as well. I'm comfortable doing this in the PHP, but I don't know where the change should be made.

**Comment by ravishakya** [comment]
Hi,

1. I have added options to change labels of the name, email, website and comment.
2. You can hide the predefined fields ( Name, email , website and comment as well )

Plz check and confirm so i can update it to the wordpress.org

Thanks

**Comment by KTDesigns** [comment]
The form works perfectly, thank you!
