### ISSUE TITLE
Form defaults when not logged in

### ISSUE THREAD

**Issue by KTDesigns** [ravishakya/comment-form-builder#3]
When I'm logged into my Wordpress site I see all the custom fields I've made (although I've yet to be able to replace the default fields with my own), but when I'm logged out (as anyone commenting will be), all I see is the default Name, Email, Add Comment, and URL fields.

**Comment by ravishakya** [comment]
Which theme you are using?? It the theme from https://wordpress.org/themes ( Free ) or custom made theme ?

**Comment by KTDesigns** [comment]
This is the Nevia theme (https://themeforest.net/item/nevia-responsive-multipurpose-wordpress-theme/4118819).

**Comment by ravishakya** [comment]
I have made some changes on the plugin. Now it should work. You can download the plugin from [here](https://github.com/ravishakya/comment-form-builder/archive/master.zip)
