### ISSUE TITLE
Comments not held for moderation

### ISSUE THREAD

**Issue by KTDesigns** [ravishakya/comment-form-builder#5]
I have my site set to moderate all comments. I've noticed that when I post a test comment while logged out, it gets displayed even if I haven't approved it yet. When I'm logged in, I don't see the unapproved comments. (I still get the email notice, although it doesn't show the extra fields I've added.) If I mark them as trash, they disappear from the logged-out side. Does this have something to do with this plugin?

**Comment by ravishakya** [comment]
It is the default feature of the WordPress. When a guest post a comment it will be displayed to them only as a preview. The extra fields will not be added in the mail. I have tried to add them in the mail but there were problems.
